# Use the latest version of the Rust base image
FROM rust:latest

RUN apt-get update && apt-get install -y cmake

RUN mkdir /opt/producer
# Set the working directory in the container to /my
WORKDIR /opt/producer
# Copy the Rust project files to the working directory
COPY . .
# Build the Rust app
RUN cargo build
# Set the command to run the Rust app
CMD cargo run